title: Articles
description: My Personal Stack Problems
author: Mochammad Rafi
github: https://github.com/kol4k
about: I am freelance developer. Currently doing more in backend, focused in C++/C and PHP.
disqus_shortname: kol4k
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://facebook.com/kol4k"
    - icon: fa-twitter
      link: "https://twitter.com/r777_01"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-instagram
      link: "https://instagram.com/rafalrzkn"
    - icon: fa-github
      link: "https://github.com/kol4k"

share:
  twitter_username: r777_01
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://kol4k.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
